module.exports = {
    purchase: '00'
  , preauth: '01'
  , preauthComplete: '02'
  , forcedPost: '03'
  , refund: '04'
  , preauthOnly: '05'
  , paypalOrder: '07'
  , 'void': '13'
  , taggedPreauthComplete: '32'
  , taggedVoid: '33'
  , taggedRefund: '34'
  , cashout: '83'
  , activation: '85'
  , balanceInquiry: '86'
  , reload: '88'
  , deactivation: '89'
};