// https://firstdata.zendesk.com/entries/450214-supported-currencies
// https://firstdata.zendesk.com/entries/61756929-GGe4-Supported-Currencies

module.exports = {
  USD: "U.S. Dollar",
  CAD: "Canadian Dollar",
  DEM: "German Mark",
  CHF: "Swiss Franc",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AFA: "Afghanistan Afghani",
  ALL: "Albanian Lek",
  DZD: "Algerian Dinar",
  ADF: "Andorran Franc",
  ADP: "Andorran Peseta",
  AON: "Angolan New Kwanza",
  ARS: "Argentine Peso",
  AWG: "Aruban Florin",
  AUD: "Australian Dollar",
  ATS: "Austrian Schilling",
  BSD: "Bahamanian Dollar",
  BHD: "Bahraini Dinar",
  BDT: "Bangladeshi Taka",
  BBD: "Barbados Dollar",
  BEF: "Belgian Franc",
  BZD: "Belize Dollar",
  BMD: "Bermudian Dollar",
  BTN: "Bhutan Ngultrum",
  BOB: "Bolivian Boliviano",
  BWP: "Botswana Pula",
  BRL: "Brazilian Real",
  BND: "Brunei Dollar",
  BGL: "Bulgarian Lev",
  BIF: "Burundi Franc",
  XOF: "CFA Franc BCEAO",
  XAF: "CFA Franc BEAC",
  KHR: "Cambodian Riel",
  CVE: "Cape Verde Escudo",
  KYD: "Cayman Islands Dollar",
  CLP: "Chilean Peso",
  CNY: "Chinese Yuan Renminbi",
  COP: "Colombian Peso",
  KMF: "Comoros Franc",
  CRC: "Costa Rican Colon",
  HRK: "Croatian Kuna",
  CYP: "Cyprus Pound",
  CSK: "Czech Koruna",
  DKK: "Danish Krone",
  DJF: "Djibouti Franc",
  DOP: "Dominican Peso",
  NLG: "Dutch Guilder",
  XEU: "ECU",
  ECS: "Ecuador Sucre",
  EGP: "Egyptian Pound",
  SVC: "El Salvador Colon",
  EEK: "Estonian Kroon",
  ETB: "Ethiopian Birr",
  EUR: "Euro",
  FKP: "Falkland Islands Pound",
  FJD: "Fiji Dollar",
  FIM: "Finnish Markka",
  FRF: "French Franc",
  GMD: "Gambian Dalasi",
  GHC: "Ghanaian Cedi",
  GIP: "Gibraltar Pound",
  XAU: "Gold (oz.)",
  GRD: "Greek Drachma",
  GTQ: "Guatemalan Quetzal",
  GNF: "Guinea Franc",
  GYD: "Guyanan Dollar",
  HTG: "Haitian Gourde",
  HNL: "Honduran Lempira",
  HKD: "Hong Kong Dollar",
  HUF: "Hungarian Forint",
  ISK: "Iceland Krona",
  INR: "Indian Rupee",
  IDR: "Indonesian Rupiah",
  IEP: "Irish Punt",
  ILS: "Israeli New Shekel",
  ITL: "Italian Lira",
  JMD: "Jamaican Dollar",
  JOD: "Jordanian Dinar",
  KZT: "Kazakhstan Tenge",
  KES: "Kenyan Shilling",
  KWD: "Kuwaiti Dinar",
  LAK: "Lao Kip",
  LVL: "Latvian Lats",
  LSL: "Lesotho Loti",
  LRD: "Liberian Dollar",
  LTL: "Lithuanian Litas",
  LUF: "Luxembourg Franc",
  MOP: "Macau Pataca",
  MGF: "Malagasy Franc",
  MWK: "Malawi Kwacha",
  MYR: "Malaysian Ringgit",
  MVR: "Maldive Rufiyaa",
  MTL: "Maltese Lira",
  MRO: "Mauritanian Ouguiya",
  MUR: "Mauritius Rupee",
  MXN: "Mexican Peso",
  MNT: "Mongolian Tugrik",
  MAD: "Moroccan Dirham",
  MZM: "Mozambique Metical",
  MMK: "Myanmar Kyat",
  ANG: "NL Antillian Guilder",
  NAD: "Namibia Dollar",
  NPR: "Nepalese Rupee",
  NZD: "New Zealand Dollar",
  NIO: "Nicaraguan Cordoba Oro",
  NGN: "Nigerian Naira",
  NOK: "Norwegian Kroner",
  OMR: "Omani Rial",
  PKR: "Pakistan Rupee",
  XPD: "Palladium (oz.)",
  PAB: "Panamanian Balboa",
  PGK: "Papua New Guinea Kina",
  PYG: "Paraguay Guarani",
  PEN: "Peruvian Nuevo Sol",
  PHP: "Philippine Peso",
  XPT: "Platinum (oz.)",
  PLN: "Polish Zloty",
  PTE: "Portuguese Escudo",
  QAR: "Qatari Rial",
  ROL: "Romanian Leu",
  RUB: "Russian Rouble",
  WST: "Samoan Tala",
  STD: "Sao Tome/Principe Dobra",
  SAR: "Saudi Riyal",
  SCR: "Seychelles Rupee",
  SLL: "Sierra Leone Leone",
  XAG: "Silver (oz.)",
  SGD: "Singapore Dollar",
  SKK: "Slovak Koruna",
  SIT: "Slovenian Tolar",
  SBD: "Solomon Islands Dollar",
  ZAR: "South African Rand",
  KRW: "South-Korean Won",
  ESP: "Spanish Peseta",
  LKR: "Sri Lanka Rupee",
  SHP: "St. Helena Pound",
  SRG: "Suriname Guilder",
  SZL: "Swaziland Lilangeni",
  SEK: "Swedish Krona",
  TWD: "Taiwan Dollar",
  TZS: "Tanzanian Shilling",
  THB: "Thai Baht",
  TOP: "Tonga Pa'anga",
  TTD: "Trinidad/Tobago Dollar",
  TND: "Tunisian Dinar",
  TRL: "Turkish Lira",
  UGS: "Uganda Shilling",
  UAH: "Ukraine Hryvnia",
  UYP: "Uruguayan Peso",
  AED: "Utd. Arab Emir. Dirham",
  VUV: "Vanuatu Vatu",
  VEB: "Venezuelan Bolivar",
  VND: "Vietnamese Dong",
  YUN: "Yugoslav Dinar",
  ZMK: "Zambian Kwacha"
}
