// eCommerce Response Codes (ETG [e4 Transaction Gateway] Codes)
// https://firstdata.zendesk.com/entries/451980-ecommerce-response-codes-etg-codes

module.exports = {
    // This response code indicates that the transaction was processed normally.
    // Please refer to the bank and approval response information for bank approval
    // Status.
    '00' : 'Transaction Normal',
    
    // UNDOCUMENTED!!!!!
    '01' : 'Unable to Exchange Key Info',
    '09' : 'Transaction Reversed',
    '13' : 'Required Field ID Missing',
    '29' : 'Manual Card Entry Only',
    '33' : 'Merchant Volume Exceeded',
    '34' : 'Card Volume Exceeded',
    '35' : 'Maximum Sale Exceeded',
    '36' : 'Below Minimum Sale',
    '38' : 'Transaction Count Exceeded (Card)',
    '39' : 'Transaction Count Exceeded (IP Address)',
    '45' : 'Transaction Code Blocked',
    '46' : 'Invalid Batch Number',
    '47' : 'Non-Verified 3-D Secure Tx',
    '48' : 'Invalid SST Data',
    '51' : 'Data Direct Transaction Test',
    '59' : 'Unable to Update Database',
    '65' : 'Transaction Voided by Client',
    '66' : 'Call Auth. Centre',
    '67' : 'Transaction Option Not Supported',
    '69' : 'Invalid Transaction Tag',
    '71' : 'Transaction Popped from Queue',
    '74' : 'Transaction Returned to Client',
    '75' : 'Transaction Acknowledged',
    '98' : 'Record Sent to Bank',
    '99' : 'Record Read from File',

    // The following response codes indicate invalid data in the transaction.
    // In these cases, the data should be changed before attempting to resend
    // the transaction. These response codes are generated by the remote 
    // Plug-In. They will not appear on the First Data Global Gateway e4
    // website.
    '08' : 'CVV2/CID/CVC2 Data not verified',
    '22' : 'Invalid Credit Card Number',
    '25' : 'Invalid Expiry Date',
    '26' : 'Invalid Amount',
    '27' : 'Invalid Card Holder',
    '28' : 'Invalid Authorization No',
    '31' : 'Invalid Verification String',
    '32' : 'Invalid Transaction Code',
    '57' : 'Invalid Reference No',
    '58' : 'Invalid AVS String, The length of the AVS String has exceeded the max. 40 characters',
    '60' : 'Invalid Customer Reference Number',
    '63' : 'Invalid Duplicate',
    '64' : 'Invalid Refund',
    '68' : 'Restricted Card Number',
    '72' : 'Data within the transaction is incorrect', // Transaction Sent to Bank
    '93' : 'Invalid authorization number entered on a pre-auth completion',
    // The following response codes indicate a problem with the merchant 
    // configuration at the financial institution. Please contact First Data
    // for further investigation.
    '11' : 'Invalid Sequence No',
    '12' : 'Message Timed-out at Host',
    '21' : 'BCE Function Error',
    '23' : 'Invalid Response from Vital',
    '30' : 'Invalid Date From Host',
    // The following response codes indicate a problem with the Global Gateway
    // e4 host or an error in the merchant configuration. Please contact First 
    // Data for further investigation.
    '10' : 'Invalid Transaction Description',
    '14' : 'Invalid Gateway ID',
    '15' : 'Invalid Transaction Number',
    '16' : 'Connection Inactive',
    '17' : 'Unmatched Transaction',
    '18' : 'Invalid Reversal Response',
    '19' : 'Unable to Send Socket Transaction',
    '20' : 'Unable to Write Transaction to File',
    '24' : 'Unable to Void Transaction',
    '37' : 'Payment Type Not Supported By Merchant',
    '40' : 'Unable to Connect',
    '41' : 'Unable to Send Logon',
    '42' : 'Unable to Send Trans',
    '43' : 'Invalid Logon',
    '52' : 'Terminal not Activated',
    '53' : 'Terminal/Gateway Mismatch',
    '54' : 'Invalid Processing Center',
    '55' : 'No Processors Available',
    '56' : 'Database Unavailable',
    '61' : 'Socket Error', // Internal Network Error
    '62' : 'Host not Ready',
    // The following response codes indicate the final state of a transaction.
    // In the event of one of these codes being returned, please contact First
    // Data for further investigation.
    '44' : 'Address not Verified',
    '70' : 'Transaction Placed in Queue',
    '73' : 'Transaction Received from Bank',
    '76' : 'Reversal Pending',
    '77' : 'Reversal Complete',
    '79' : 'Reversal Sent to Bank',
    // The following response codes indicate the final state of a transaction
    // due to custom Fraud Filters created by the Merchant.
    'F1' : 'Address check failed - Fraud suspected',
    'F2' : 'Card/Check Number check failed - Fraud suspeted',
    'F3' : 'Country Check Failed - Fraud suspected',
    'F4' : 'Customer Reference Check Failed - Fraud suspected',
    'F5' : 'Email Address checked failed - Fraud suspected',
    'F6' : 'IP Address check failed - Fraud suspected'
};